spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    driver-class-name: org.postgresql.Driver
    generate-unique-name: false
    name: spring-boot-library
    url: jdbc:postgresql://localhost:5433/spring-boot-library
    username: postgres
    password: postgres
  mvc:
    hidden-method:
      filter:
        enabled: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
