create table if not exists Person(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname varchar(250),
    lastname varchar(250),
    email varchar(250) UNIQUE,
    age int check ( age > 0 ),
    birthYear int
);

create table if not exists Book(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(500),
    author varchar(500),
    year int
);